### ISSUE TITLE
Error when using cleveref

### ISSUE THREAD

**Issue by jossTheBoss** [jeslago/optidef#8]
Hi,
I am using optidef and get an error when using \label commands in the mini! environment. I have found that this problem occurs as soon as I use the package cleveref. Here is some MWE:

\documentclass{article}

\usepackage[nocomma,short]{optidef}
\usepackage{cleveref}

\begin{document}

	
\begin{mini!}
	{x}{\sum_{i = 1}^{n} y_i}{}{}
	\addConstraint{y_i}{\leq t_i \label{test}\qquad }{ i \in \{1,\dots,n\}}
\end{mini!}
	
\end{document}

Commenting cleveref out resolves the issue.

**Comment by jeslago** [comment]
You are the second one that mentions the issue. I need to update the documentation to address this problem.

I think the issue should be solved if you import the cleveref package before the optidef. Can you try that and let me know if it works?

**Comment by jossTheBoss** [comment]
It does indeed solve the problem for the MWE, unfortunately, it did not resolve the error for my actual project. I digged a little and found the following MWE:

\documentclass{article}


\usepackage{amsmath}
\usepackage{cleveref}
\usepackage[nocomma,short]{optidef}


\begin{document}

	
\begin{mini!}
	{x}{\sum_{i = 1}^{n} y_i}{}{}
	\addConstraint{y_i}{\leq t_i \label{test}\qquad }{ i \in \{1,\dots,n\}}
\end{mini!}
	
\end{document}

This yields the same error as before. However if I import amsmath after cleveref and before optidef, the error goes away.

**Comment by jeslago** [comment]
That problem might be addressed in the documentation of cleveref, Section 13:

http://mirrors.rit.edu/CTAN/macros/latex/contrib/cleveref/cleveref.pdf

In the documentation says that all the packages that don't specifically support cleveref should be loaded after cleveref. However, the amsmath package should support it. I should look more into it, in any case I am glad it was solved for you already.

**Comment by jossTheBoss** [comment]
I find it super strange that the error only occurs in combination with optidef, because if I don't include optidef, the order of amsmath and cleveref does not seem to matter.
Anyway, thank you for the quick reply and the overall great package!

**Comment by jeslago** [comment]
Yes I have also noticed that. But if you remove the cleveref package, then the order of optidef and asmath also does not matter, and even if you leave the cleveref package, the order of optidef and asmath does not matter. I need to look more into it, and maybe see if I can add support to use the cleveref package without any issue.

**Comment by jeslago** [comment]
Hi again,

I think I know how to solve the problem. Can you try to load the cleveref package as the last one and protect all your labels, i.e. use \protect\label{foo} instead of \label{foo}?

**Comment by jeslago** [comment]
I am closing the problem as it seems to be solved. I have updated the documentation to the explain the clashes between optidef and the cleveref package. 

In short, if using the cleveref and the optidef package, load the cleveref package the last. Moreover, If using the command `\label` in the optidef environment, protect it by using `\protect\label`.
